### PR TITLE
add a way, however clumsy, to use lowercase table names

### PR DESCRIPTION
**Pull request by RussNelson**

### CODE REVIEW

**Comment by jseppi** [comment]
Hi @RussNelson -- It's been a long time since I've worked on this project, and I'm not really involved with CUAHSI much any more, but as I recall, those table names are from the CUAHSI ODM schema (http://his.cuahsi.org/odmdatabases.html). I don't have a way currently to open the sample databases linked on that page, but I believe they use the upper-case table names, and this example was showing specifically how to hook up WOFpy to an ODM-based database.

**Comment by RussNelson** [comment]
Couldn't get it to work with MySQL without lower-case table names. SQLalchemy recommends using lower-case table names.

**Comment by jseppi** [comment]
Since the modified file in this PR is in the example for the SQL Server-based ODM (`examples/odm_sqlserver/`), perhaps a more appropriate place would be to create a new example folder and implementation for a MySQL-based ODM.

**Comment by RussNelson** [comment]
Sure. I'll work on it.

**Comment by twhiteaker** [comment]
If making an ODM MySQL example, you might find HydroServer resources for a [MySQL ODM database](https://hydroserver.codeplex.com/wikipage?title=Observations%20Data%20Model) and [PHP WaterOneFlow service](https://hydroserver.codeplex.com/wikipage?title=WaterOneFlow%20Web%20Service%20for%20PHP) helpful.

**Comment by RussNelson** [comment]
Yup, I'm going to at least write a readme pointing to them.  Might be worthwhile setting up a pre-configured Amazon Web Services instance that somebody can just fire-up.

**Pull request closed without merging**
