### PR TITLE
Added WOF 1.1, and updated WML2 output

### PR DESCRIPTION
**Pull request by valentinedwv**

### CODE REVIEW

**Comment by wilsaj** [comment]
Neat - I'm really glad that you've picked up WOFpy and are making use of it. Would you like to become maintainers? We are not currently running or working on WOFpy, so it's hard to keep track of the codebase and give meaningful feedback on PRs and such.

**Comment by valentinedwv** [comment]
Sure.

**Comment by valentinedwv** [comment]
And it looks like Choonhan has made a request.... like me, he was probably
thinking it was going to our repo.

**Comment by valentinedwv** [comment]
And any idea on how to transfer the PyPi responsibilities?

**Comment by wilsaj** [comment]
Actually, my thought now is to just have a soft transfer to the ODM2/WOFpy repo since swtools isn't really a thing and you have a lot of other good stuff going on over in that ODM2 org. The way I've seen this work for similar situations is that we would update the README for swtools/WOFpy saying this repo is deprecated and people should go to ODM2/WOFpy to find the currently maintained WOFpy. We need to keep a stable copy of our version here because some of the work was grant funded and this url might have been attached to important money-related documents. You can choose whether or not you want to keep ODM2/WOFpy as a github fork or re-publish if you want to break the link (so it won't say forked from swtools/WOFpy). We can't automatically transfer the issues if we go this soft transfer route, but most of those are stale anyway.

You can take over the pypi publishing completely. If you send me your pypi username(s), I'll add you as owners/maintainers and then you should be able to publish.

Sound good?

**Comment by valentinedwv** [comment]
yes.
pypi id is valentinedwv

**Comment by wilsaj** [comment]
Updated the README and I've added you as an owner on pypi. As far as I can tell, you should be able to push updates and all the various admin things. Let me know if that isn't working.

**Comment by valentinedwv** [comment]
Moved to ODM2/WofPy

**Pull request closed without merging**
